version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - DSN=${DSN}
      - PS_DB_HOST=${PS_DB_HOST}
      - PS_DB_PORT=${PS_DB_PORT}
      - PS_DB_USER=${PS_DB_USER}
      - PS_DB_PASS=${PS_DB_PASS}
      - PS_DB_NAME=${PS_DB_NAME}
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - app-network

  lint:
    build:
      context: .
      dockerfile: Dockerfile.lint
    depends_on:
      - app

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${PS_DB_PASS}
      - MYSQL_DATABASE=${PS_DB_NAME}
      - MYSQL_USER=${PS_DB_USER}
      - MYSQL_PASSWORD=${PS_DB_PASS}
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
