# ビルドステージ
FROM golang:1.21.3 AS builder

# golangci-lintのインストール
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.40.1

WORKDIR /app
COPY . .

# ランタイムステージ
FROM golang:1.21.3

# ビルドステージからgolangci-lintバイナリをコピー
COPY --from=builder /go/bin/golangci-lint /go/bin/golangci-lint

WORKDIR /app
COPY . .

# golangci-lint の実行
CMD ["/go/bin/golangci-lint", "run"]
